- name: Tomcat deployment playbook
  hosts: database             # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: kumar         # Update username for remote server
  roles:
   - mysql
